- name: create pgsql data dir
  file:
    path: "{{ item }}"
    owner: postgres
    group: postgres
    mode: 0750
    state: directory
  with_items:
   - "{{ PG_DATA }}"

- name: config postgresql-11.service
  template:
    src: postgresql-11.service.j2
    dest: "/usr/lib/systemd/system/postgresql-11.service"

- name: register pg_data
  shell: "ls {{ PG_DATA }}"
  register: pg_data

- name: init data
  shell: "sudo -u postgres /usr/pgsql-11/bin/pg_basebackup -h {{ groups.master[0] }} -p 5432 -U {{ REPLICATION_USER }} -F p -P -D {{ PG_DATA }} -w"
  args:
    chdir: /var/lib/pgsql
  when: pg_data.stdout == ""

- name: config pg_hba.conf
  template:
    src: pg_hba.conf.j2
    dest: "{{ PG_DATA }}/pg_hba.conf"
    owner: postgres
    owner: postgres

- name: config recovery.conf
  template:
    src: recovery.conf.j2
    dest: "{{ PG_DATA }}/recovery.conf"
    owner: postgres
    owner: postgres

- name: config postgresql.conf
  template:
    src: postgresql.conf.j2
    dest: "{{ PG_DATA }}/postgresql.conf"
    owner: postgres
    owner: postgres

- name: start slave pgsql
  systemd:
    state: restarted
    name: postgresql-11

