- name: start zookeeper
  hosts: all
  remote_user: "{{ username }}"
  gather_facts: false
  tasks:
  - name: stop zookeeper
    shell:
      "{{ ZOOKEEPER_DIR }}/zookeeper/bin/zkServer.sh start"
    ignore_errors: True
  tags:
    - start

- name: clean all
  hosts: all
  gather_facts: false
  tasks:
  - name: remove java
    sudo: yes
    remote_user: root
    yum:
      name: "{{ item }}"
      state: absent
    with_items:
     - java-1.8.0-openjdk
     - java-1.8.0-openjdk-devel
  - name: clean data dir
    file:
      path: "{{ item }}" 
      state: absent
    with_items:
     - "{{ ZOOKEEPER_DIR }}"
     - "{{ DATA_DIR }}"
     - "{{ DATA_LOG_DIR }}"
  tags:
   - clean
