---

- name: bootstrap
  hosts: all
  gather_facts: false
  roles:
    - bootstrap
  tags:
    - bootstrap

- name: deploy zookeeper
  hosts: all
  remote_user: "{{ username }}"
  gather_facts: false
  roles:
    - deploy-zookeeper
  tags:
    - deploy

- name: start zookeeper
  hosts: all
  gather_facts: false
  tasks:
  - name: start zookeeper
    systemd:
      state: started
      name: zookeeper
      daemon_reload: yes
      enabled: yes
  tags:
    - start
