---
- name: install java
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - java-1.8.0-openjdk
    - java-1.8.0-openjdk-devel

- name: deploy spark
  copy:
    src: "{{ VERSION }}.tgz"
    dest: "{{ SPARK_DIR }}/"

- name: decompression spark
  shell: |
    cd {{ SPARK_DIR }}
    tar xf {{ VERSION }}.tgz 
    mv {{ VERSION }} spark


- name: generate conf/spark-env.sh
  template:
    src: spark-env.sh.j2
    dest: "{{ SPARK_DIR }}/spark/conf/spark-env.sh"
    mode: 0755
