---

- name: install java
  sudo: yes
  remote_user: root
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - java-1.8.0-openjdk
    - java-1.8.0-openjdk-devel  

- name: create dir
  sudo: yes
  remote_user: root
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
  with_items:
   - "{{ ZOOKEEPER_DIR }}"

- name: decompression zookeeper
  unarchive:
    src: "{{ VERSION }}.tar.gz"
    dest: "{{ ZOOKEEPER_DIR }}"

- name: add zookeeper link
  file:
    src: "{{ ZOOKEEPER_DIR }}/{{ VERSION }}"
    path: "{{ ZOOKEEPER_DIR }}/zookeeper"
    state: link

- name: create dir
  sudo: yes
  remote_user: root
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
  with_items:
   - "{{ DATA_DIR }}"
   - "{{ DATA_LOG_DIR }}"

- name: init DIR and myid
  lineinfile:
    path: "{{ DATA_DIR }}/myid"
    line: "{{ myid }}"
    create: yes

- name: generate zoo.cfg
  template:
    src: zoo.cfg.j2
    dest: "{{ ZOOKEEPER_DIR }}/zookeeper/conf/zoo.cfg"

