- name: decompression hadoop
  unarchive:
    src: "{{ HADOOP_VERSION }}.tar.gz"
    dest: "{{ HADOOP_DIR }}"

- name: add hadoop link
  file:
    src: "{{ HADOOP_DIR }}/{{ HADOOP_VERSION }}"
    path: "{{ HADOOP_DIR }}/hadoop"
    state: link

- name: add env
  lineinfile:
    path:  ~/.bashrc
    line: '{{ item }}'
  with_items:
    - export HADOOP_HOME="{{ HADOOP_DIR }}/hadoop"
    - export PATH="$HADOOP_HOME/bin:$PATH"
    - export HADOOP_INSTALL=$HADOOP_HOME
    - export HADOOP_MAPRED_HOME=$HADOOP_HOME
    - export HADOOP_COMMON_HOME=$HADOOP_HOME
    - export HADOOP_HDFS_HOME=$HADOOP_HOME
    - export YARN_HOME=$HADOOP_HOME
    - export HADOOP_YARN_HOME=$HADOOP_HOME
    - export HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_HOME/lib/native
    - export PATH=$PATH:$HADOOP_HOME/sbin:$HADOOP_HOME/bin

- name: create dir
  sudo: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
  with_items:
   - "{{ HADOOP_DIR }}"
   - "{{ DFS_NAMENODE_NAME_DIR }}"
   - "{{ DFS_DATANODE_DATA_DIR }}"
   - "{{ DFS_NAMENODE_CHECKPOINE_DIR }}"
   - "{{  YARN_NODEMANAGER_LOCAL_DIRS }}"
   - "{{ YARN_NODEMANAGER_REMOTE_APP_LOG_DIR }}"
