- name: judge a file or dir is exits
  shell: ls "{{ DFS_NAMENODE_NAME_DIR }}/current"
  ignore_errors: True
  register: result

- shell: "{{ HADOOP_DIR }}/hadoop/bin/hdfs namenode -format"
  when: result is failed 
