---

- name: config hadoop-env.sh
  lineinfile:
    path: "{{ HADOOP_DIR }}/hadoop/etc/hadoop/hadoop-env.sh"
    line: '{{ item }}'
  with_items:
    - export JAVA_HOME="{{ JAVA_DIR }}/java"
    - export HADOOP_HOME="{{ HADOOP_DIR }}/hadoop"
    - export PATH=${PATH}:${HADOOP_HOME}/bin

- name: config core-site.xml 
  template:
    src: core-site.xml.j2
    dest: "{{ HADOOP_DIR }}/hadoop/etc/hadoop/core-site.xml"
  when: mode == "single"


- name: config core-site.xml 
  template:
    src: core-site.xml-ha.j2
    dest: "{{ HADOOP_DIR }}/hadoop/etc/hadoop/core-site.xml"
  when: mode == "ha"

- name: config hdfs-site.xml
  template:
    src: hdfs-site.xml.j2
    dest: "{{ HADOOP_DIR }}/hadoop/etc/hadoop/hdfs-site.xml"
  when: mode == "single"


- name: config hdfs-site.xml
  template:
    src: hdfs-site.xml-ha.j2
    dest: "{{ HADOOP_DIR }}/hadoop/etc/hadoop/hdfs-site.xml"
  when: mode == "ha"

- name: config mapred-site.xml
  template:
    src: mapred-site.xml.j2
    dest: "{{ HADOOP_DIR }}/hadoop/etc/hadoop/mapred-site.xml"
  when: mode == "single"


- name: config mapred-site.xml
  template:
    src: mapred-site.xml-ha.j2
    dest: "{{ HADOOP_DIR }}/hadoop/etc/hadoop/mapred-site.xml"
  when: mode == "ha"

- name: config yarn-site.xml 
  template:
    src: yarn-site.xml.j2
    dest: "{{ HADOOP_DIR }}/hadoop/etc/hadoop/yarn-site.xml"
  when: mode == "single"


- name: config yarn-site.xml 
  template:
    src: yarn-site.xml-ha.j2
    dest: "{{ HADOOP_DIR }}/hadoop/etc/hadoop/yarn-site.xml"
  when: mode == "ha"

- name: config workers
  template:
    src: workers.j2
    dest: "{{ HADOOP_DIR }}/hadoop/etc/hadoop/workers"
  when: mode == "single"


- name: config workers
  template:
    src: workers-ha.j2
    dest: "{{ HADOOP_DIR }}/hadoop/etc/hadoop/workers"
  when: mode == "ha"
