---

- name: start hadoop master
  hosts: master
  gather_facts: false
  tasks:
  - name: start master
    shell: |
      hdfs --daemon start namenode
      hdfs --daemon start secondarynamenode
      hdfs --daemon start datanode
      yarn --daemon start resourcemanager
      yarn --daemon start nodemanager
  tags:
    - start

- name: start hadoop node
  hosts: node
  gather_facts: false
  tasks:
  - name: start node
    shell: |
      hdfs --daemon start namenode
      hdfs --daemon start secondarynamenode
      hdfs --daemon start datanode
      yarn --daemon start resourcemanager
      yarn --daemon start nodemanager
  tags:
    - start