---

- name: start hadoop master
  hosts: master
  gather_facts: false
  remote_user: "{{ username }}"
  tasks:
  - name: start master
    shell: |
      nohup hdfs --daemon start namenode &
      nohup hdfs --daemon start secondarynamenode &
      nohup hdfs --daemon start datanode &
      nohup yarn --daemon start resourcemanager &
      nohup yarn --daemon start nodemanager &
  tags:
    - start

- name: start hadoop node
  hosts: node
  gather_facts: false
  remote_user: "{{ username }}"
  tasks:
  - name: start node
    shell: |
      nohup hdfs --daemon start namenode &
      nohup hdfs --daemon start secondarynamenode &
      nohup hdfs --daemon start datanode &
      nohup yarn --daemon start resourcemanager &
      nohup yarn --daemon start nodemanager &
  tags:
    - start
