---
- name: deploy kafka
  hosts: all
  gather_facts: false
  roles:
    - bootstrap
  tags:
   - bootstrap

- name: deploy kafka
  hosts: all
  remote_user: "{{ username }}"
  gather_facts: false
  roles:
    - deploy-kafka
  tags:
    - deploy

- name: start kafka
  hosts: all
  gather_facts: false
  tasks:
  - name: start kafka
    systemd:
      state: started
      name: kafka
      daemon_reload: yes
      enabled: yes
  tags:
    - start
