- name: create dir
  file:
    path: "{{ repodir }}"
    state: directory


- name: install mysql repo
  unarchive:
    src: "myrepo.tar"
    dest: "{{ repodir }}"


- name: Add myrepo repositories
  yum_repository:
    name: myrepo
    description: my repo
    file: my_repos
    baseurl: "file://{{ repodir }}/myrepo"
    enabled: yes
    gpgcheck: no
